### ISSUE TITLE
Modules wont work

### ISSUE THREAD

**Issue by Timo2805** [AlessandroZ/LaZagne#416]
Today i tried to run Lazagne to get some old passwords back the only problem is other than the Wifi and System Hash Modules nothing works. Lazagne starts up then prints the wifi passwords and windows user hashes and after that it just gets stuck i tried waiting for 10 minutes but nothing. A long time ago i used lazagne the same way as now and everything worked only difference is it was on windows 8 not 10. I would be happy if anyone could help me out with this.

**Comment by Papotito123** [comment]
Hi:
First,antivirus as Defender/Avast can block it or make it run inaccurate.
Second,Be sure to run lazagne with Run As ...
Third ,latest version has some issues.
Try version 2.3.2.Is some slow but works good.
As for Windows 10(1803 and newer) some dependencies/permissions really do its job.
NTLM hashes retrieved are not real ones.Look closely.
If you had run maintenance programs maybe some of the credentials/passwords are cleared .
At least,I has been using this tool for some years.

**Comment by AlessandroZ** [comment]
Hi @Papotito123, 

I would be happy to understand why NTLM hashes are not real ones and why the latest version does not work properly. I will be happy to correct bugs if you find ones.  

@Timo2805, launch lazagne in verbose mode with `-vvv`

**Comment by Papotito123** [comment]
Thank you for being aware of your work.
I don't speak English perfectly. Any mistake is the fault of Google Translate.
I'm not a coder,a programmer,not even a computer genius.
I'm just an enthusiastic guy with little experience here and there.
As for others,I recognize this is a pretty good tool.So thanks.

I launched lazagne in verbose mode with -vvv.I'm sending a file.

Thanks for be part in this.
[Papotito123_lazagne 2.4.2_logfile.txt](https://github.com/AlessandroZ/LaZagne/files/3576961/Papotito123_lazagne.2.4.2_logfile.txt)

**Comment by AlessandroZ** [comment]
Thanks @Papotito123 for your feedback. 

If you look closely your report, you only have 2 errors
``` 
------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\TESTACCOUNT\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: c:\users\testac~1\appdata\local\temp\eadmtmqbh
[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000001BC1D7A5FAD
```
And this one: 
```
[+] File written: C:\Users\TESTACCOUNT\Desktop\lazagne v2.4.2\credentials_04092019_201357.json
[-] Error parsing the json results: 'list' object has no attribute 'keys'
```

I see that you are using the last release, but it's not up to date. Lots of errors have been corrected and I'm pretty sure the second error has already been fixed. It could be awesome, if you could try the last version (using the python code). 

The first one is a real problem that I cannot reproduce and I don't know if it's still present or not. If you want to confirm it, please try using the python code and give me the feedback. It's easy to test, install python on your windows, and install requirements. 
`python.exe -m pip install -r requirements.txt`

All other messages are not issues. 
I should change the message from vnc module to not appear like an error. It's not a problem, it's just that the path of the file does not exists. 
```
[!] Problems with file: C:\Program Files (x86)\uvnc bvba\UltraVNC\ultravnc.ini
```

Messages saying `[-] xxxxxx not ok for masterkey xxxxxx` are not issues. It means that the windows system password has not been found but it tries to find it using all previous passwords found (from wifi, etc.) and trying all usernames found as well (to find peolple using same password and username). 

The last version is much more advanced than the others. Maybe the Google chrome is a real problem that I should fixed but right now I cannot reproduce it, so it's quite difficult for me. Maybe the last version already correct it. If you can confirm it, it should be great. 

Thanks.

**Comment by Papotito123** [comment]
Hello:
While I'm dealing with the phyton thing,I just send this to compare with lazagne 2.4.2 behaviour.
These are lazagne 2.3.2 output files ,with just edited the email account/passwords retrieved.

[Papotito123_lazagne v2.3.2.log](https://github.com/AlessandroZ/LaZagne/files/3581676/Papotito123_lazagne.v2.3.2.log)
[Papotito123_lazagne v2.3.2.txt](https://github.com/AlessandroZ/LaZagne/files/3581677/Papotito123_lazagne.v2.3.2.txt)

**Comment by Papotito123** [comment]
Hello:
I think I installed python(at last).

When running  lazagne.py gives me error.Maybe I missing something.
Thanks in advanced.

I sent a raw cmd 
[Papotito123_lazagne.py v2.4.2_cmd error.txt](https://github.com/AlessandroZ/LaZagne/files/3581735/Papotito123_lazagne.py.v2.4.2_cmd.error.txt)
copy/paste.

**Comment by Papotito123** [comment]
Hello:
Well, Python 3.7 doesn't works good in Win 10.Please forget about No module named 'd3des error.
So I installed Python 2.7.16 and managed to run laZagne.py.

I sent 2 -vvv -oA output files.And sent a raw copy/paste from the cmd that has more info
It recovers Chrome user/password. Good.

But still throwing a placeholder dummy NTLM hash  for users accounts.

Also in lazagne.exe v2.4.2,, it's some kind of cosmetic, but output in .txt is not same as the .json and not equal as .log.
Chrome user/password was retrieved fine in lazagne.exe 2.3.2.And output files are more organized.

My best shot is to have an .exe that works reliable that can be run from a pendrive when relatives/friends ask me to for retrieving some info(in a ethical manner of speaking) from it's computers.
How can I do with lazagne? 

[Papotito123_lazagne.py v2.4.2_raw cmd.txt](https://github.com/AlessandroZ/LaZagne/files/3581993/Papotito123_lazagne.py.v2.4.2_raw.cmd.txt)
[Papotito123_lazagne.py v2.4.2.txt](https://github.com/AlessandroZ/LaZagne/files/3581994/Papotito123_lazagne.py.v2.4.2.txt)

Thanks for your time and for being part of this.

**Comment by AlessandroZ** [comment]
Thanks for all your outputs, it helps me to understand. 

I think that you still not using the last version because the error `[-] Error parsing the json results: 'list' object has no attribute 'keys'` should either be corrected (I'm pretty sure it had been corrected) or printing a stacktrace. 

You could get the last python code here: https://github.com/AlessandroZ/LaZagne/archive/master.zip

If you could try again and give me the ouput it could be awesome. For me, you should have no error with json and chrome and wifi passwords printed. 

The output organisation has not changed between version, you should see results sorted by users, etc... I agree that now, you have more outputs so it could be confusing. 

I have noticed, that the DPAPI hash is not printed anymore which it's not normal (I should take a look on this). 

I don't understand why you say that NTLM hashes are wrong ? For example, here: 
```
Administrator:500:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
```

- Administrator: username
- 500: rid
- aad3b435b51404eeaad3b435b51404ee: LM hash (empty value)
- 31d6cfe0d16ae931b73c59d7e0c089c0: NT hash

Be carefult, that DPAPI hash are totally different: 
```
Dpapi_hash_local: $DPAPImk$2*1*S-1-5-21-337365419-192549521-2618175838-1002*aes256*sha512*8000*a6339ee815987716a531b88ce754d725*288*d122e297ff76cc2e52df83dd5bb0cbc38047fc0b20490d43b36583b2cd3310f9441c085fe3c68f3add556b534ff222d89b79076609c57db4e3b9d8c9597808f6a853572ec08dbd17e1ed29b3bb5bffd9b127f900058c4621379b72083c5cdd311299cd6c454412a1aa2a4540ff160e035a5d73aa01ce6b7a670f6f81206ed5878ce8d69d21974d5329596ba636526a0d
```
Which can be used to be bruteforced to detect the user password but cannot be used for NTLM attacks.

**Comment by Timo2805** [comment]
Thanks for the answer AlessandroZ i had a lot of work to do so it took some time for me to answer. I tried it in Verbose mode and now it gets to Wsl passwords where its stuck again.. would be apprecheated if you could help me out one more time.

**Comment by AlessandroZ** [comment]
@Timo2805, I cannot helo without any output.

**Comment by Papotito123** [comment]
Hello:
These are all outputs with laZagne.py latest link you sent.

As I can see now, I thought I had sent you *.json files but this site doesn't support it.
*.log files were output but didn't notice weren't sent.
I just add .txt at end.

[Papotito123_laZagne.py_latest.txt](https://github.com/AlessandroZ/LaZagne/files/3586078/Papotito123_laZagne.py_latest.txt)
[Papotito123_laZagne.py_latest_raw cmd.txt](https://github.com/AlessandroZ/LaZagne/files/3586079/Papotito123_laZagne.py_latest_raw.cmd.txt)

[Papotito123_laZagne.py_latest.json.txt](https://github.com/AlessandroZ/LaZagne/files/3586082/Papotito123_laZagne.py_latest.json.txt)


Thanks.

**Comment by Papotito123** [comment]
Hello:
[Papotito123_laZagne_NTLM hashes.txt](https://github.com/AlessandroZ/LaZagne/files/3586097/Papotito123_laZagne_NTLM.hashes.txt)

**Comment by AlessandroZ** [comment]
Hi, 

I have seen the error concerning the NTLM hashes (I didn't understand the problem yet but I will take a look). 

But I have still have a problem with your lazagne version because the output is not like it should be. On the last version, you should have the [python banner](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/write_output.py#L52) printed when debug mode is used: 
```
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[!] Python 2.7.15 on Windows AMD64: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

```
Then your error: 
```
[-] Error parsing the json results: 'list' object has no attribute 'keys'
```
I don't even understand why it appears, because 'keys' has been removed some time ago (check the [commit](https://github.com/AlessandroZ/LaZagne/commit/e2958aea1a8fd114c1295d4d045f1a3fc72d1c0f#diff-db94a635b0bc1f93b0c6a5290053eeaeL327)). And you should not see an error line but a full [stacktrace](https://github.com/AlessandroZ/LaZagne/commit/e2958aea1a8fd114c1295d4d045f1a3fc72d1c0f#diff-db94a635b0bc1f93b0c6a5290053eeaeL335). 

I have [updated](https://github.com/AlessandroZ/LaZagne/commit/f62e53857b32557932e98287e34195b7f8956d3b) the version to be sure you are using the last version. Run: 
```
lazagne.exe -version
```
You should have 2.4.2.1 now. Thanks for your help. 

I still confirm that DPAPI hashes are not printed and NTLM hashes are still not valid  on the last version. These problems should be corrected.

**Comment by AlessandroZ** [comment]
NTLM problem should be fixed. I have update the version to be sure you use the last one: 
Lazagne version should print 2.4.2.2. 

Thanks

**Comment by Papotito123** [comment]
Hello;
Here are the outputs and some more from lazagne.py  2.4.2.2 
[Papotito123_lazagne.py v2.4.2.2_MORE INFO.txt](https://github.com/AlessandroZ/LaZagne/files/3593358/Papotito123_lazagne.py.v2.4.2.2_MORE.INFO.txt)

[Papotito123_lazagne.py v2.4.2.2.json.txt](https://github.com/AlessandroZ/LaZagne/files/3593359/Papotito123_lazagne.py.v2.4.2.2.json.txt)

[Papotito123_lazagne.py v2.4.2.2_raw cmd.txt](https://github.com/AlessandroZ/LaZagne/files/3593360/Papotito123_lazagne.py.v2.4.2.2_raw.cmd.txt)

[Papotito123_lazagne.py v2.4.2.2.txt](https://github.com/AlessandroZ/LaZagne/files/3593361/Papotito123_lazagne.py.v2.4.2.2.txt)

Things are getting better.
Thank you.

**Comment by Papotito123** [comment]
Hello:
And for your benefit , I compiled lazagne.py v2.4.2.2 to .exe.

And these are the outputs.Improving for good.

[Papotito123_lazagne 2.4.2.2_compiled_raw cmd.txt](https://github.com/AlessandroZ/LaZagne/files/3593403/Papotito123_lazagne.2.4.2.2_compiled_raw.cmd.txt)

[Papotito123_lazagne 2.4.2.2_compiled.json.txt](https://github.com/AlessandroZ/LaZagne/files/3593404/Papotito123_lazagne.2.4.2.2_compiled.json.txt)

[Papotito123_lazagne 2.4.2.2_compiled.txt](https://github.com/AlessandroZ/LaZagne/files/3593405/Papotito123_lazagne.2.4.2.2_compiled.txt)

Thanks.

**Comment by AlessandroZ** [comment]
Except your files containing compiled info, you didn't use the last version again. You didn't specify the good path launching the tool:
```
C:\Python27>python.exe "C:\laza\LaZagne-master_2.4.2.2\Windows\laZagne.py" => it was the good one
C:\Python27>lazagne.py -version => then you called an older one
Version 2.4.2 => wrong version
C:\Python27>laZagne.py all -vvv -oA -output "C:\Python27" => so this call is wrong
```
Anyway, this is not a problem. As I understood, you do not have more errors except for Chrome passwords. 
```
[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 116, in _export_credentials
  File "lazagne\config\winstructure.py", line 587, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 542, in getData
WindowsError: exception: access violation reading 0x000004F2A4663E2D
```
On all your outputs, I cannot understand when this error occurs and when it worked. Because, it worked with older version like 2.3.2, 2.4.2 (compiled exe) and you have an output running 2.4.2 with python which work so I don't understand. And fails with 2.4.2.2. 

I have tried to reproduce the error but it never occurs. So I need your help to understand what's going on. 

Please remove all your old lazagne version and download the last one to be sure you use the good version (2.4.2.2). 
Try it multiple times to be sure you always have the chrome error. Then find an older version of lazagne that work. 
Add a print after this line (`print(repr(cipherText)`): https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/winstructure.py#L567

Add some prints here to print cbData, pbData and buffer: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/winstructure.py#L541

And compare the version which work and the one which fails. 

But remove all your previous versions because you confuse a lot with your lazagne path and I loose some time to try to understand what's happening :+1: 

Thanks for your help.

**Comment by Papotito123** [comment]
Hello:
Sorry for any trouble about my folders nomenclature.

I try to do most of that you ask.
Sorry for what I can't.

[Papotito123_v2.4.2.2_latest__Some Info.txt](https://github.com/AlessandroZ/LaZagne/files/3597724/Papotito123_v2.4.2.2_latest__Some.Info.txt)

[Papotito123_v2.4.2.2_latest__raw cmd.txt](https://github.com/AlessandroZ/LaZagne/files/3597725/Papotito123_v2.4.2.2_latest__raw.cmd.txt)

[Papotito123_v2.4.2.2_latest.json.txt](https://github.com/AlessandroZ/LaZagne/files/3597726/Papotito123_v2.4.2.2_latest.json.txt)

[Papotito123_v2.4.2.2_latest.txt](https://github.com/AlessandroZ/LaZagne/files/3597727/Papotito123_v2.4.2.2_latest.txt)

If you want it, I can send lazagne 2.4.2.2_latest  compiled to .exe outputs.

Thanks.

**Comment by AlessandroZ** [comment]
Sorry but I give up. I spend too much time checking your outputs to finally seeing that you still not use the last version. I was not talking about your folder nomenclature but about which version you execute and the output you printed does not looks like the last version. 

Thanks for your time by the way. Sorry to not help you more.

**Comment by Papotito123** [comment]
Hello:
So much thanks for your effort 
I'm so pretty sure I used the latest version 2 4.2.2 according the page.I verified for the modified files.I used lazagne.py and also I compiled it to .exe.The results are not the same.That's my biggest concern and it's my strong effort to make you noticed.As now for me it's not an issue to have to compile lazagne.py to exe to get the latest version because after some attempts I finally made the goal to install Python and compiled.Moreover I finally get installed and run lazagneForensic. 
In the last version I downloaded from https://github.com/AlessandroZ/LaZagne/archive/master.zip, I see that in the end,with this downloaded latest laZagne.py, NTLM hashes are not good but it recovered Chrome/Firefox passwords.
And with the compiled.exe from this downloaded latest laZagne, NTLM hashes are the real ones but Chrome paswords are not recovered.And the output *.txt looks more good.
I see improving but still inconsistency,at least for Windows 10 1809 64bit .In a Windows 10 10240 lasagne exe works good.
Again,so much thanks for your time,effort and patience.
I hope this interaction with a real person with real a OS will give you the benefit to continue improving your tool.
And I will still seeking,testing and using your lazagne.

With much gratitude ,so much thanks.

**Comment by Papotito123** [comment]
Hello:
Sorry for any Awkward situation.After some hours uninstalling.deleting and reinstalling I finally make the things as should be.And the central joint in this was that I found a \AppData\Local\Programs\Python37 folder remanent that indeed had a lazagne.py inside.After this , things works as you expected.
I used the latest lazagne 2.4.2.2 code and also I compile it to .exe. Also I finally add the Print lines you asked before.
Output are close to perfect.Chrome user/passwords are retrieved and NTLM hashes are good.

I'm not so smart but I am persistent when have a doubt and try to find the answer.
And I took your advice about old installations.Well I have to search for some time until I found a  Python37 folder remanent with lazagne.py 2.4.2.

Thanks for the opportunity to let me find the right way.

Just if you want it to see;

[Papotito123_2.4.2.2_REAL_raw cmd.txt](https://github.com/AlessandroZ/LaZagne/files/3603786/Papotito123_2.4.2.2_REAL_raw.cmd.txt)

Thank  you.
